
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  name: 'name',
  role: 'role',
  engineerRole: 'engineerRole',
  position: 'position',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  message: 'message',
  link: 'link',
  isRead: 'isRead',
  createdAt: 'createdAt'
};

exports.Prisma.MaterialRequestScalarFieldEnum = {
  id: 'id',
  docControlNo: 'docControlNo',
  projectId: 'projectId',
  projectName: 'projectName',
  assignSys: 'assignSys',
  assignPM: 'assignPM',
  workPackage: 'workPackage',
  wpo: 'wpo',
  keterangan: 'keterangan',
  status: 'status',
  fileUrl: 'fileUrl',
  dateReleased: 'dateReleased',
  requestedBy: 'requestedBy',
  wpoApprovedBy: 'wpoApprovedBy',
  wpoApprovedAt: 'wpoApprovedAt',
  systemApprovedBy: 'systemApprovedBy',
  systemApprovedAt: 'systemApprovedAt',
  pmApprovedBy: 'pmApprovedBy',
  pmApprovedAt: 'pmApprovedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MaterialRequestItemScalarFieldEnum = {
  id: 'id',
  materialRequestId: 'materialRequestId',
  description: 'description',
  elsicomPartNum: 'elsicomPartNum',
  manufacturePartNum: 'manufacturePartNum',
  type: 'type',
  manufacturer: 'manufacturer',
  qty: 'qty',
  unit: 'unit',
  targetDate: 'targetDate',
  remarks: 'remarks'
};

exports.Prisma.FaultReportScalarFieldEnum = {
  id: 'id',
  docNo: 'docNo',
  projectId: 'projectId',
  projectName: 'projectName',
  itemName: 'itemName',
  manufacturer: 'manufacturer',
  targetRepair: 'targetRepair',
  faultIssue: 'faultIssue',
  priority: 'priority',
  status: 'status',
  description: 'description',
  reportedBy: 'reportedBy',
  approvalStatus: 'approvalStatus',
  wpoApprovedBy: 'wpoApprovedBy',
  wpoApprovedAt: 'wpoApprovedAt',
  systemApprovedBy: 'systemApprovedBy',
  systemApprovedAt: 'systemApprovedAt',
  pmApprovedBy: 'pmApprovedBy',
  pmApprovedAt: 'pmApprovedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WarehouseReleaseScalarFieldEnum = {
  id: 'id',
  docNo: 'docNo',
  materialRequestId: 'materialRequestId',
  projectId: 'projectId',
  projectName: 'projectName',
  deliveryTarget: 'deliveryTarget',
  deliveryLocation: 'deliveryLocation',
  releaseDate: 'releaseDate',
  dateReleased: 'dateReleased',
  requesterId: 'requesterId',
  status: 'status',
  warehouseApprovedBy: 'warehouseApprovedBy',
  warehouseApprovedAt: 'warehouseApprovedAt',
  procurementApprovedBy: 'procurementApprovedBy',
  procurementApprovedAt: 'procurementApprovedAt',
  rejectedSide: 'rejectedSide',
  rejectedReason: 'rejectedReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WarehouseReleaseItemScalarFieldEnum = {
  id: 'id',
  warehouseReleaseId: 'warehouseReleaseId',
  reqNo: 'reqNo',
  requestor: 'requestor',
  approval: 'approval',
  description: 'description',
  elsPartNum: 'elsPartNum',
  manufacturer: 'manufacturer',
  requestQty: 'requestQty',
  remainingQty: 'remainingQty',
  qty: 'qty',
  unit: 'unit'
};

exports.Prisma.InventoryScalarFieldEnum = {
  id: 'id',
  itemName: 'itemName',
  sku: 'sku',
  stockQty: 'stockQty',
  unit: 'unit'
};

exports.Prisma.SuratJalanScalarFieldEnum = {
  id: 'id',
  materialRequestId: 'materialRequestId',
  driverName: 'driverName',
  vehiclePlate: 'vehiclePlate',
  issuedAt: 'issuedAt'
};

exports.Prisma.PurchaseOrderScalarFieldEnum = {
  id: 'id',
  poNumber: 'poNumber',
  projectId: 'projectId',
  projectCode: 'projectCode',
  supplierName: 'supplierName',
  termOfPayment: 'termOfPayment',
  deliveryTime: 'deliveryTime',
  poDate: 'poDate',
  status: 'status',
  poHealth: 'poHealth',
  totalAmount: 'totalAmount',
  currency: 'currency',
  notes: 'notes',
  materialRequestId: 'materialRequestId',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.POItemScalarFieldEnum = {
  id: 'id',
  poId: 'poId',
  description: 'description',
  partNumber: 'partNumber',
  qty: 'qty',
  unit: 'unit',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice',
  prNo: 'prNo',
  prDate: 'prDate',
  prProcessDate: 'prProcessDate',
  matIn: 'matIn',
  receivedQty: 'receivedQty',
  mrItemId: 'mrItemId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.POInvoiceScalarFieldEnum = {
  id: 'id',
  poId: 'poId',
  invoiceNo: 'invoiceNo',
  invoiceDate: 'invoiceDate',
  amount: 'amount',
  isPaid: 'isPaid',
  paidAt: 'paidAt',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.BorrowedItemScalarFieldEnum = {
  id: 'id',
  docNo: 'docNo',
  fromProjectId: 'fromProjectId',
  fromProjectName: 'fromProjectName',
  toProjectId: 'toProjectId',
  toProjectName: 'toProjectName',
  description: 'description',
  partNumber: 'partNumber',
  qty: 'qty',
  unit: 'unit',
  notes: 'notes',
  borrowDate: 'borrowDate',
  dueDate: 'dueDate',
  status: 'status',
  returnedAt: 'returnedAt',
  returnNotes: 'returnNotes',
  processedBy: 'processedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProjectBudgetScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  year: 'year',
  budget: 'budget',
  currency: 'currency',
  inputBy: 'inputBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupplierPriceScalarFieldEnum = {
  id: 'id',
  supplierName: 'supplierName',
  description: 'description',
  partNumber: 'partNumber',
  unit: 'unit',
  unitPrice: 'unitPrice',
  currency: 'currency',
  notes: 'notes',
  inputBy: 'inputBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BillOfMaterialScalarFieldEnum = {
  id: 'id',
  bomNo: 'bomNo',
  projectId: 'projectId',
  projectName: 'projectName',
  projectCode: 'projectCode',
  contractNo: 'contractNo',
  bomStatus: 'bomStatus',
  description: 'description',
  createdBy: 'createdBy',
  submittedBy: 'submittedBy',
  wpoApprovedBy: 'wpoApprovedBy',
  wpoApprovedAt: 'wpoApprovedAt',
  wpoRemarks: 'wpoRemarks',
  systemApprovedBy: 'systemApprovedBy',
  systemApprovedAt: 'systemApprovedAt',
  systemRemarks: 'systemRemarks',
  pricedBy: 'pricedBy',
  pricedAt: 'pricedAt',
  procurementNotes: 'procurementNotes',
  assignedToStaff: 'assignedToStaff',
  assignedToWpo: 'assignedToWpo',
  assignedToSystem: 'assignedToSystem',
  refinementStartedAt: 'refinementStartedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  submittedAt: 'submittedAt'
};

exports.Prisma.BomItemScalarFieldEnum = {
  id: 'id',
  bomId: 'bomId',
  marketingDesc: 'marketingDesc',
  marketingQty: 'marketingQty',
  marketingUnit: 'marketingUnit',
  itemStatus: 'itemStatus',
  refinedDesc: 'refinedDesc',
  refinedQty: 'refinedQty',
  refinedUnit: 'refinedUnit',
  specifications: 'specifications',
  notes: 'notes',
  refinedBy: 'refinedBy',
  refinedAtStaff: 'refinedAtStaff',
  refinedByWpo: 'refinedByWpo',
  refinedAtWpo: 'refinedAtWpo',
  refinedBySystem: 'refinedBySystem',
  refinedAtSystem: 'refinedAtSystem',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice',
  currency: 'currency',
  supplier: 'supplier',
  leadTime: 'leadTime',
  pricedBy: 'pricedBy',
  pricedAt: 'pricedAt',
  rejectionReason: 'rejectionReason',
  hasSubItems: 'hasSubItems',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BomSubItemScalarFieldEnum = {
  id: 'id',
  bomItemId: 'bomItemId',
  description: 'description',
  qty: 'qty',
  unit: 'unit',
  specifications: 'specifications',
  notes: 'notes',
  sortOrder: 'sortOrder',
  unitPrice: 'unitPrice',
  totalPrice: 'totalPrice',
  currency: 'currency',
  supplier: 'supplier',
  leadTime: 'leadTime',
  pricedBy: 'pricedBy',
  pricedAt: 'pricedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.BomHistoryScalarFieldEnum = {
  id: 'id',
  bomId: 'bomId',
  action: 'action',
  performedBy: 'performedBy',
  details: 'details',
  previousData: 'previousData',
  newData: 'newData',
  timestamp: 'timestamp'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.UserOrderByRelevanceFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  name: 'name',
  position: 'position'
};

exports.Prisma.NotificationOrderByRelevanceFieldEnum = {
  id: 'id',
  userId: 'userId',
  message: 'message',
  link: 'link'
};

exports.Prisma.MaterialRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  docControlNo: 'docControlNo',
  projectId: 'projectId',
  projectName: 'projectName',
  assignSys: 'assignSys',
  assignPM: 'assignPM',
  workPackage: 'workPackage',
  wpo: 'wpo',
  keterangan: 'keterangan',
  fileUrl: 'fileUrl',
  requestedBy: 'requestedBy',
  wpoApprovedBy: 'wpoApprovedBy',
  systemApprovedBy: 'systemApprovedBy',
  pmApprovedBy: 'pmApprovedBy'
};

exports.Prisma.MaterialRequestItemOrderByRelevanceFieldEnum = {
  materialRequestId: 'materialRequestId',
  description: 'description',
  elsicomPartNum: 'elsicomPartNum',
  manufacturePartNum: 'manufacturePartNum',
  type: 'type',
  manufacturer: 'manufacturer',
  unit: 'unit',
  remarks: 'remarks'
};

exports.Prisma.FaultReportOrderByRelevanceFieldEnum = {
  id: 'id',
  docNo: 'docNo',
  projectId: 'projectId',
  projectName: 'projectName',
  itemName: 'itemName',
  manufacturer: 'manufacturer',
  faultIssue: 'faultIssue',
  description: 'description',
  reportedBy: 'reportedBy',
  wpoApprovedBy: 'wpoApprovedBy',
  systemApprovedBy: 'systemApprovedBy',
  pmApprovedBy: 'pmApprovedBy'
};

exports.Prisma.WarehouseReleaseOrderByRelevanceFieldEnum = {
  id: 'id',
  docNo: 'docNo',
  materialRequestId: 'materialRequestId',
  projectId: 'projectId',
  projectName: 'projectName',
  deliveryTarget: 'deliveryTarget',
  deliveryLocation: 'deliveryLocation',
  requesterId: 'requesterId',
  warehouseApprovedBy: 'warehouseApprovedBy',
  procurementApprovedBy: 'procurementApprovedBy',
  rejectedSide: 'rejectedSide',
  rejectedReason: 'rejectedReason'
};

exports.Prisma.WarehouseReleaseItemOrderByRelevanceFieldEnum = {
  warehouseReleaseId: 'warehouseReleaseId',
  reqNo: 'reqNo',
  requestor: 'requestor',
  approval: 'approval',
  description: 'description',
  elsPartNum: 'elsPartNum',
  manufacturer: 'manufacturer',
  unit: 'unit'
};

exports.Prisma.InventoryOrderByRelevanceFieldEnum = {
  id: 'id',
  itemName: 'itemName',
  sku: 'sku',
  unit: 'unit'
};

exports.Prisma.SuratJalanOrderByRelevanceFieldEnum = {
  id: 'id',
  materialRequestId: 'materialRequestId',
  driverName: 'driverName',
  vehiclePlate: 'vehiclePlate'
};

exports.Prisma.PurchaseOrderOrderByRelevanceFieldEnum = {
  id: 'id',
  poNumber: 'poNumber',
  projectId: 'projectId',
  projectCode: 'projectCode',
  supplierName: 'supplierName',
  termOfPayment: 'termOfPayment',
  currency: 'currency',
  notes: 'notes',
  materialRequestId: 'materialRequestId',
  createdBy: 'createdBy'
};

exports.Prisma.POItemOrderByRelevanceFieldEnum = {
  id: 'id',
  poId: 'poId',
  description: 'description',
  partNumber: 'partNumber',
  unit: 'unit',
  prNo: 'prNo'
};

exports.Prisma.POInvoiceOrderByRelevanceFieldEnum = {
  id: 'id',
  poId: 'poId',
  invoiceNo: 'invoiceNo',
  notes: 'notes'
};

exports.Prisma.BorrowedItemOrderByRelevanceFieldEnum = {
  id: 'id',
  docNo: 'docNo',
  fromProjectId: 'fromProjectId',
  fromProjectName: 'fromProjectName',
  toProjectId: 'toProjectId',
  toProjectName: 'toProjectName',
  description: 'description',
  partNumber: 'partNumber',
  unit: 'unit',
  notes: 'notes',
  returnNotes: 'returnNotes',
  processedBy: 'processedBy'
};

exports.Prisma.ProjectBudgetOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  currency: 'currency',
  inputBy: 'inputBy'
};

exports.Prisma.SupplierPriceOrderByRelevanceFieldEnum = {
  id: 'id',
  supplierName: 'supplierName',
  description: 'description',
  partNumber: 'partNumber',
  unit: 'unit',
  currency: 'currency',
  notes: 'notes',
  inputBy: 'inputBy'
};

exports.Prisma.BillOfMaterialOrderByRelevanceFieldEnum = {
  id: 'id',
  bomNo: 'bomNo',
  projectId: 'projectId',
  projectName: 'projectName',
  projectCode: 'projectCode',
  contractNo: 'contractNo',
  description: 'description',
  createdBy: 'createdBy',
  submittedBy: 'submittedBy',
  wpoApprovedBy: 'wpoApprovedBy',
  wpoRemarks: 'wpoRemarks',
  systemApprovedBy: 'systemApprovedBy',
  systemRemarks: 'systemRemarks',
  pricedBy: 'pricedBy',
  procurementNotes: 'procurementNotes',
  assignedToStaff: 'assignedToStaff',
  assignedToWpo: 'assignedToWpo',
  assignedToSystem: 'assignedToSystem'
};

exports.Prisma.BomItemOrderByRelevanceFieldEnum = {
  id: 'id',
  bomId: 'bomId',
  marketingDesc: 'marketingDesc',
  marketingUnit: 'marketingUnit',
  refinedDesc: 'refinedDesc',
  refinedUnit: 'refinedUnit',
  specifications: 'specifications',
  notes: 'notes',
  refinedBy: 'refinedBy',
  refinedByWpo: 'refinedByWpo',
  refinedBySystem: 'refinedBySystem',
  currency: 'currency',
  supplier: 'supplier',
  pricedBy: 'pricedBy',
  rejectionReason: 'rejectionReason'
};

exports.Prisma.BomSubItemOrderByRelevanceFieldEnum = {
  id: 'id',
  bomItemId: 'bomItemId',
  description: 'description',
  unit: 'unit',
  specifications: 'specifications',
  notes: 'notes',
  currency: 'currency',
  supplier: 'supplier',
  pricedBy: 'pricedBy'
};

exports.Prisma.BomHistoryOrderByRelevanceFieldEnum = {
  id: 'id',
  bomId: 'bomId',
  action: 'action',
  performedBy: 'performedBy',
  details: 'details',
  previousData: 'previousData',
  newData: 'newData'
};
exports.Role = exports.$Enums.Role = {
  ENGINEER: 'ENGINEER',
  PROCUREMENT: 'PROCUREMENT',
  MARKETING: 'MARKETING',
  WPO: 'WPO',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  FINANCE: 'FINANCE',
  WAREHOUSE: 'WAREHOUSE'
};

exports.EngineerRole = exports.$Enums.EngineerRole = {
  STAFF: 'STAFF',
  WPO: 'WPO',
  SYSTEM: 'SYSTEM'
};

exports.Status = exports.$Enums.Status = {
  WAITING_WPO: 'WAITING_WPO',
  WAITING_SYSTEM: 'WAITING_SYSTEM',
  WAITING_PM: 'WAITING_PM',
  APPROVED: 'APPROVED',
  PROCUREMENT_PROCESS: 'PROCUREMENT_PROCESS',
  FINANCE_PAID: 'FINANCE_PAID',
  AVAILABLE_IN_WAREHOUSE: 'AVAILABLE_IN_WAREHOUSE',
  SHIPPED: 'SHIPPED',
  REJECTED: 'REJECTED'
};

exports.Priority = exports.$Enums.Priority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.FaultStatus = exports.$Enums.FaultStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  CLOSED: 'CLOSED'
};

exports.WrStatus = exports.$Enums.WrStatus = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  WAREHOUSE_APPROVED: 'WAREHOUSE_APPROVED',
  PROCUREMENT_APPROVED: 'PROCUREMENT_APPROVED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  SHIPPED: 'SHIPPED'
};

exports.POStatus = exports.$Enums.POStatus = {
  DRAFT: 'DRAFT',
  RELEASED: 'RELEASED',
  PARTIAL_RECEIVED: 'PARTIAL_RECEIVED',
  FULL_RECEIVED: 'FULL_RECEIVED',
  CANCELLED: 'CANCELLED'
};

exports.POHealth = exports.$Enums.POHealth = {
  ON_TRACK: 'ON_TRACK',
  WARNING: 'WARNING',
  CRITICAL: 'CRITICAL',
  LATE: 'LATE',
  RECEIVED: 'RECEIVED'
};

exports.BorrowStatus = exports.$Enums.BorrowStatus = {
  BORROWED: 'BORROWED',
  RETURNED: 'RETURNED'
};

exports.BomStatus = exports.$Enums.BomStatus = {
  DRAFT: 'DRAFT',
  SUBMITTED: 'SUBMITTED',
  WPO_REVIEW: 'WPO_REVIEW',
  WPO_APPROVED: 'WPO_APPROVED',
  WPO_REJECTED: 'WPO_REJECTED',
  SYSTEM_REVIEW: 'SYSTEM_REVIEW',
  SYSTEM_APPROVED: 'SYSTEM_APPROVED',
  SYSTEM_REJECTED: 'SYSTEM_REJECTED',
  REJECTED: 'REJECTED',
  ACTIVE: 'ACTIVE',
  PRICED: 'PRICED',
  ARCHIVED: 'ARCHIVED'
};

exports.BomItemStatus = exports.$Enums.BomItemStatus = {
  PENDING: 'PENDING',
  REFINED: 'REFINED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PRICED: 'PRICED'
};

exports.Prisma.ModelName = {
  User: 'User',
  Notification: 'Notification',
  MaterialRequest: 'MaterialRequest',
  MaterialRequestItem: 'MaterialRequestItem',
  FaultReport: 'FaultReport',
  WarehouseRelease: 'WarehouseRelease',
  WarehouseReleaseItem: 'WarehouseReleaseItem',
  Inventory: 'Inventory',
  SuratJalan: 'SuratJalan',
  PurchaseOrder: 'PurchaseOrder',
  POItem: 'POItem',
  POInvoice: 'POInvoice',
  BorrowedItem: 'BorrowedItem',
  ProjectBudget: 'ProjectBudget',
  SupplierPrice: 'SupplierPrice',
  BillOfMaterial: 'BillOfMaterial',
  BomItem: 'BomItem',
  BomSubItem: 'BomSubItem',
  BomHistory: 'BomHistory'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
